const responses = {
    // General greetings
    'hello': 'Hello! How can I assist you today?',
    'hi': 'Hello! How can I assist you today?',
    'hey': 'Hello! How can I assist you today?',
    'hi there': 'Hello! How can I assist you today?',
    'hello there': 'Hello! How can I assist you today?',
    'greetings': 'Hello! How can I assist you today?',
    'howdy': 'Hello! How can I assist you today?',
    'hey there': 'Hello! How can I assist you today?',

    // Other greetings
    'good morning': 'Good day! How can I assist you today?',
    'good afternoon': 'Good day! How can I assist you today?',
    'good evening': 'Good day! How can I assist you today?',
    'good day': 'Good day! How can I assist you today?',

    // Inquiry responses
    'how are you': 'I’m just a bot, but I’m here and ready to help you!',
    'how’s it going': 'I’m just a bot, but I’m here and ready to help you!',
    'how are things': 'I’m just a bot, but I’m here and ready to help you!',
    'how’s everything': 'I’m just a bot, but I’m here and ready to help you!',
    'how’s your day': 'I’m just a bot, but I’m here and ready to help you!',

    // Casual responses
    'what’s up': 'Not much, just here to assist you. How can I help?',
    'what’s new': 'Not much, just here to assist you. How can I help?',
    'what’s happening': 'Not much, just here to assist you. How can I help?',

    // Offering assistance
    'how can I help you': 'I’m here to assist you with whatever you need. How can I help?',
    'how can I assist you': 'I’m here to assist you with whatever you need. How can I help?',
    'welcome': 'I’m here to assist you with whatever you need. How can I help?',

    // Group greetings
    'hi everyone': 'Good to see you! How can I help you today?',
    'hello everyone': 'Good to see you! How can I help you today?',
    'hi folks': 'Good to see you! How can I help you today?',
    'good to see you': 'Good to see you! How can I help you today?',
    'nice to meet you': 'Good to see you! How can I help you today?',
    'pleased to meet you': 'Good to see you! How can I help you today?',

    // Farewell messages
    'thank you': 'You\'re welcome! If you have any other questions, feel free to ask.',
    'bye': 'Goodbye! Have a great day!',
    'goodbye': 'Goodbye! Have a great day!',
    'see you later': 'See you later! Have a wonderful day!',
    'talk to you soon': 'Talk to you soon! Don’t hesitate to reach out if you need help.',
    'take care': 'Take care! Have a great day!',
    'farewell': 'Farewell! Have a fantastic day!',
    'catch you later': 'Catch you later! Have a great day!',
    'until next time': 'Until next time! Take care!',
    'see you soon': 'See you soon! Have a wonderful day!',
    'have a good one': 'Have a good one! Take care!',
    'stay safe': 'Stay safe! Have a great day!',
    'all the best': 'All the best! Have a wonderful day!',
    'bye for now': 'Bye for now! See you soon!',
    'have a nice day': 'Have a nice day! Take care!',
    'see you around': 'See you around! Have a great day!',
    'later': 'Later! Have a good one!',
    'peace out': 'Peace out! Take care!',
    'adios': 'Adios! Have a great day!',
    'ciao': 'Ciao! See you soon!',
    'take it easy': 'Take it easy! Have a great day!',
    'bye-bye': 'Bye-bye! Stay safe!',
    'so long': 'So long! Have a wonderful day!',
    'godspeed': 'Godspeed! Take care!',
    'until we meet again': 'Until we meet again! Stay safe!',
    'see you in a bit': 'See you in a bit! Take care!',
    'keep in touch': 'Keep in touch! Have a great day!',
    'stay well': 'Stay well! See you soon!',
    'stay in touch': 'Stay in touch! Have a wonderful day!',
    'see ya': 'See ya! Have a great one!',
    'take it slow': 'Take it slow! Have a good day!',
    'it was nice talking to you': 'It was nice talking to you! Take care!',
    'catch you on the flip side': 'Catch you on the flip side! Stay safe!',
    'until later': 'Until later! Have a good one!',
    'have a safe trip': 'Have a safe trip! See you soon!',
    'cheerio': 'Cheerio! Take care!',
    'toodles': 'Toodles! Have a great day!',
    'god bless': 'God bless! Stay safe!',
    'be well': 'Be well! Have a great day!',
    'so long for now': 'So long for now! Take care!',
    'see you when I see you': 'See you when I see you! Have a good one!',
    'stay awesome': 'Stay awesome! Have a wonderful day!',
    'good night': 'Good night! Sweet dreams!',
    'sweet dreams': 'Sweet dreams! Take care!',
    'over and out': 'Over and out! See you soon!',
    'good evening': 'Good evening! Take care!',
    'till we talk again': 'Till we talk again! Have a great day!',
    'look after yourself': 'Look after yourself! Have a wonderful day!',
    'stay positive': 'Stay positive! See you soon!',
    'keep smiling': 'Keep smiling! Take care!',


    // QHSE-related
    'qhse': 'QHSE stands for Quality, Health, Safety, and Environment. It encompasses all practices and standards aimed at ensuring quality, safety, and environmental compliance within an organization.',
    'importance of qhse': 'The importance of QHSE lies in its ability to improve organizational performance, ensure compliance with legal and regulatory requirements, enhance employee safety, and minimize environmental impact.',
    'qhse standards': 'QHSE standards are guidelines and requirements set to ensure quality, health, safety, and environmental management. Common standards include ISO 9001 for quality, ISO 45001 for occupational health and safety, and ISO 14001 for environmental management.',
    'how to implement qhse': 'Implementing QHSE involves establishing policies and procedures, conducting risk assessments, providing training, monitoring performance, and ensuring compliance with relevant standards and regulations.',
    'qhse policy': 'A QHSE policy outlines an organization\'s commitment to quality, health, safety, and environmental management. It sets the framework for managing QHSE aspects and achieving continuous improvement.',

    // Audit-related
    'audit': 'The Audit and Inspection Module helps in managing audits and inspections effectively. You can schedule audits, track findings, and generate reports.',
    'audit findings': 'Audit findings are the results of an audit process that identifies non-conformities, areas for improvement, and compliance with standards.',
    'audit schedule': 'You can schedule audits to ensure regular review and compliance with QHSE standards.',
    'audit checklist': 'An audit checklist includes all the criteria and areas to be reviewed during an audit, helping ensure a thorough evaluation.',
    'internal audit': 'Internal audits are conducted by the organization to evaluate its own QHSE processes and ensure compliance with internal policies and standards.',
    'external audit': 'External audits are conducted by third-party organizations to assess compliance with QHSE standards and regulations.',
    'audit report': 'The audit report provides a summary of the findings, including non-conformities, areas for improvement, and recommendations for corrective actions.',

    // Document Management
    'document management': 'The Document Management System ensures that all important documents are stored, managed, and retrieved efficiently.',
    'document control': 'Document control ensures that documents are properly managed, updated, and accessible only to authorized personnel.',
    'document retention': 'Document retention policies determine how long documents should be kept before they are disposed of or archived.',
    'document versioning': 'Document versioning tracks changes to documents over time, ensuring that the latest version is always available.',
    'document approval': 'Document approval workflows ensure that documents are reviewed and approved by the appropriate personnel before they are finalized.',
    'document access': 'Document access controls ensure that sensitive documents are accessible only to authorized users.',
    'document retrieval': 'Document retrieval systems allow users to quickly search for and retrieve documents based on keywords, metadata, or other criteria.',

    // Management of Change (MOC)
    'management of change': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'moc process': 'The MOC process involves identifying, evaluating, and implementing changes in a controlled manner to minimize risks.',
    'moc approval': 'MOC approval is required before any significant change can be implemented, ensuring that all risks are assessed and managed.',
    'moc documentation': 'MOC documentation includes records of the proposed change, risk assessment, approvals, and implementation steps.',
    'moc training': 'MOC training ensures that all employees are aware of changes and understand how to implement them safely.',
    'moc communication': 'MOC communication involves informing all relevant stakeholders about changes and how they will be implemented.',
    'moc follow-up': 'MOC follow-up ensures that changes are implemented as planned and that any issues are addressed promptly.',

    // Asset Management
    'asset management': 'The Asset Management Module helps in managing the lifecycle of assets, including maintenance and performance monitoring.',
    'asset tracking': 'The Asset Tracking System helps in monitoring and managing the location, status, and condition of assets in real-time.',
    'maintenance management': 'The Maintenance Management Module schedules and tracks maintenance activities to ensure assets are operating efficiently and to prevent downtime.',
    'inventory management': 'The Inventory Management System keeps track of all assets, including their quantity, location, and usage, to optimize inventory levels.',
    'lifecycle management': 'The Asset Lifecycle Management Module oversees the entire lifecycle of assets from acquisition to disposal, ensuring maximum value and compliance.',
    'financial management': 'The Financial Management System tracks the financial performance of assets, including depreciation, cost allocation, and return on investment.',
    'performance monitoring': 'The Performance Monitoring System tracks the performance of assets to ensure they meet operational and strategic goals.',
    'procurement': 'The Procurement Module manages the acquisition of assets, ensuring cost-effectiveness and compliance with procurement policies.',
    'disposal': 'The Asset Disposal Module handles the end-of-life process for assets, including decommissioning, sale, or recycling, in a compliant and cost-effective manner.',

    // Training
    'training': 'The Training Module ensures that all employees receive the necessary training to meet compliance requirements and improve safety practices.',
    'document control': 'Document control involves managing the creation, distribution, and revision of documents to ensure accuracy, accessibility, and compliance.',

    // MOC
    'management of change': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'change management': 'Change management involves planning, implementing, and reviewing changes to ensure they are executed smoothly and do not negatively impact operations.',

    // Asset
    'asset management': 'The Asset Management Module helps in managing the lifecycle of assets, including maintenance and performance monitoring.',
    'asset tracking': 'The Asset Tracking System helps in monitoring and managing the location, status, and condition of assets in real-time.',
    'maintenance management': 'The Maintenance Management Module schedules and tracks maintenance activities to ensure assets are operating efficiently and to prevent downtime.',
    'inventory management': 'The Inventory Management System keeps track of all assets, including their quantity, location, and usage, to optimize inventory levels.',
    'lifecycle management': 'The Asset Lifecycle Management Module oversees the entire lifecycle of assets from acquisition to disposal, ensuring maximum value and compliance.',
    'financial management': 'The Financial Management System tracks the financial performance of assets, including depreciation, cost allocation, and return on investment.',
    'performance monitoring': 'The Performance Monitoring System tracks the performance of assets to ensure they meet operational and strategic goals.',
    'procurement': 'The Procurement Module manages the acquisition of assets, ensuring cost-effectiveness and compliance with procurement policies.',
    'disposal': 'The Asset Disposal Module handles the end-of-life process for assets, including decommissioning, sale, or recycling, in a compliant and cost-effective manner.',

    // Training
    'training': 'The Training Module ensures that all employees receive the necessary training to meet compliance requirements and improve safety practices.',
    'training programs': 'Training programs are designed to enhance employee skills and knowledge in specific areas to ensure competency and compliance with safety and regulatory standards.',

    // Compliance
    'compliance': 'Compliance management involves ensuring that all processes and procedures meet regulatory requirements and industry standards.',
    'policy management': 'Policy management involves creating, updating, and communicating policies to ensure adherence to organizational and regulatory standards.',
    'regulatory requirements': 'Regulatory requirements are rules and regulations established by authorities that organizations must comply with to operate legally and safely.',

    // Observation
    'observation': 'The HSE Observation System helps in recording and analyzing observations related to health, safety, and environmental practices.',
    'observation types': 'Observations can be categorized into safety observations, compliance observations, and operational observations. Each type helps address specific aspects of the workplace.',
    'handling observations': 'Handling observations involves documenting the details, assessing the significance, and taking corrective actions if needed. It\'s important to ensure that observations are followed up to improve safety and compliance.',
    'observation frequency': 'The frequency of observations depends on your organization\'s policies and the specific needs of your workplace. Regular observations help in identifying potential hazards and maintaining safety standards.',
    'follow-up actions': 'Follow-up actions on observations include reviewing the reported issue, implementing corrective measures, and monitoring the effectiveness of these measures to prevent recurrence.',
    'observation training': 'Training on observations involves educating employees on how to identify and report observations effectively. This training ensures that all personnel are aware of the importance of observations and how to document them properly.',

    // Incident
    'incident': 'The HSE Incident/Accident Management System allows you to report, track, and analyze incidents and accidents to improve safety and compliance.',
    'incident reporting': 'Incident reporting involves documenting the details of an incident as soon as it occurs. This includes the date, time, location, individuals involved, and a description of the event.',
    'incident investigation': 'Incident investigation involves analyzing the causes of an incident to identify corrective actions and prevent recurrence. This process typically includes root cause analysis and implementation of preventive measures.',
    'incident response': 'Incident response includes the actions taken immediately after an incident to address the situation, ensure safety, and mitigate any potential impacts.',
    'incident tracking': 'Incident tracking involves monitoring the progress of incident investigations, corrective actions, and resolution status to ensure all incidents are managed effectively.',
    'incident analysis': 'Incident analysis involves reviewing incident data to identify trends, patterns, and areas for improvement. This helps in enhancing safety measures and reducing the likelihood of future incidents.',
    'incident follow-up': 'Incident follow-up includes verifying that corrective actions have been implemented and assessing their effectiveness in preventing similar incidents in the future.',

    // Root Cause Analysis
    'root cause analysis': 'Root cause analysis is a method used to identify the underlying causes of problems or incidents to prevent recurrence. It involves analyzing the contributing factors and implementing corrective actions.',
    'causal analysis': 'Causal analysis involves examining the causes and effects of a problem to understand the underlying issues and develop solutions.',
    'problem-solving': 'Problem-solving involves identifying, analyzing, and resolving issues to improve processes and prevent future problems.',
    'corrective actions': 'Corrective actions are steps taken to address the root cause of a problem or incident to prevent it from happening again. This may include changes to processes, procedures, or training.',
    'preventive actions': 'Preventive actions are measures implemented to reduce the likelihood of a problem or incident occurring in the future. This can involve process improvements, additional training, or changes in procedures.',

    // Feedback
    'feedback': 'Your feedback is valuable to us. It helps improve our processes and services. Please let us know your thoughts or suggestions!',
    'feedback process': 'The feedback process involves collecting, reviewing, and acting on feedback provided by users to enhance the quality of services and address any issues or concerns.',
    'feedback implementation': 'Feedback implementation involves integrating user feedback into processes, policies, or systems to improve performance and user satisfaction.',

    // Reports
    'report': 'The Reports Module provides comprehensive reporting capabilities to track performance, compliance, and other key metrics.',
    'report generation': 'Report generation involves creating detailed reports on various aspects of your operations, including audits, incidents, and compliance status.',
    'report analysis': 'Report analysis involves reviewing and interpreting report data to gain insights and make informed decisions.',
    'report customization': 'Report customization allows you to tailor reports to meet specific needs or preferences, such as including or excluding certain data, formatting, or layout options.',
    'report distribution': 'Report distribution involves sharing reports with relevant stakeholders through various channels, such as email, dashboards, or printed copies.',

    // Safety
    'safety': 'Safety management involves implementing practices and procedures to ensure a safe working environment and reduce the risk of accidents and incidents.',
    'safety measures': 'Safety measures are actions or protocols put in place to protect employees and minimize hazards in the workplace.',
    'safety protocols': 'Safety protocols are established guidelines and procedures designed to ensure safety and compliance with regulations.',
    'safety training': 'Safety training involves educating employees on safety procedures, protocols, and best practices to ensure a safe working environment.',
    'safety policies': 'Safety policies outline the rules and expectations for maintaining a safe workplace, including reporting hazards and responding to emergencies.',
    'emergency preparedness': 'Emergency preparedness involves planning and training for potential emergencies to ensure a prompt and effective response.',

    // Health
    'health': 'Health management involves promoting and maintaining the physical and mental well-being of employees within the organization.',
    'health policies': 'Health policies outline the guidelines and procedures for maintaining employee health and well-being, including medical support, wellness programs, and health assessments.',
    'health programs': 'Health programs are initiatives designed to support and improve employee health, such as wellness programs, health screenings, and mental health support.',
    'health and safety': 'Health and safety management encompasses practices and procedures to protect employees, physical and mental health, ensuring a safe and healthy work environment.',
    'mental health': 'Mental health management involves supporting employees, mental well- being through programs, resources, and policies designed to promote mental wellness and address mental health concerns.',
    'occupational health': 'Occupational health focuses on preventing and managing health issues related to the workplace, including monitoring and addressing health risks and promoting a healthy work environment.',
    'wellness': 'Wellness programs aim to enhance employees, overall health and well - being through various activities and initiatives, such as fitness programs, nutrition guidance, and stress management.',

    // hard coded
    'what is the purpose of an audit': 'The purpose of an audit is to assess compliance with QHSE standards, identify areas for improvement, and ensure that processes meet regulatory and internal requirements.',
    'how to conduct an audit': 'Conducting an audit involves planning, creating an audit checklist, gathering evidence, evaluating processes against criteria, documenting findings, and generating an audit report.',
    'how to prepare for an audit': 'Preparation for an audit includes reviewing relevant documentation, training staff, ensuring records are up-to-date, and conducting a pre-audit to identify potential issues.',
    'what are the types of audits': 'There are several types of audits, including internal audits, external audits, compliance audits, and performance audits, each serving different purposes within QHSE management.',
    'what is an audit plan': 'An audit plan outlines the scope, objectives, timeline, and resources required for conducting an audit. It serves as a roadmap to ensure a systematic approach to the audit process.',
    'who conducts an audit': 'Audits can be conducted by internal auditors within the organization or by external auditors from third-party agencies, depending on the type and purpose of the audit.',
    'how often should audits be conducted': 'The frequency of audits depends on organizational needs, regulatory requirements, and risk levels. Regular audits are recommended to ensure continuous compliance and improvement.',
    'what is a compliance audit': 'A compliance audit is a type of audit that assesses whether an organization is adhering to laws, regulations, and internal policies related to QHSE.',
    'what is a performance audit': 'A performance audit evaluates the efficiency and effectiveness of an organization’s QHSE processes, ensuring that they achieve desired outcomes with optimal use of resources.',
    'what is the role of an audit committee': 'An audit committee oversees the audit process, ensuring that audits are conducted effectively, findings are addressed, and improvements are implemented.',
    'what is a follow-up audit': 'A follow-up audit is conducted after the initial audit to verify that corrective actions have been implemented and that previous findings have been addressed.',
    'what is a risk-based audit': 'A risk-based audit focuses on areas with the highest risk to the organization, ensuring that key vulnerabilities are identified and managed effectively.',
    'what is the audit scope': 'The audit scope defines the boundaries of the audit, including the processes, locations, and time periods to be reviewed, ensuring a focused and relevant assessment.',
    'what are audit criteria': 'Audit criteria are the standards, policies, and regulations against which the audit is conducted. They serve as benchmarks for evaluating compliance and performance.',
    'what is an audit objective': 'The audit objective is the specific goal of the audit, such as verifying compliance, assessing risk management, or evaluating process efficiency.',
    'how to schedule an audit': 'To schedule an audit, determine the frequency, select the audit team, define the scope, and set a timeline that aligns with organizational priorities and regulatory requirements.',
    'what is an audit trail': 'An audit trail is a chronological record of all the evidence and documentation reviewed during an audit. It provides transparency and supports the audit findings.',
    'how to create an audit checklist': 'To create an audit checklist, identify key areas to be reviewed, define criteria for each area, and list specific questions or items to be checked during the audit.',
    'what is the importance of an audit report': 'An audit report is important because it documents the audit findings, provides recommendations for improvement, and serves as a record for compliance verification.',
    'how to address audit findings': 'Addressing audit findings involves analyzing the root cause, developing corrective actions, implementing changes, and monitoring to ensure the issues are resolved.',

    // hard coded
    'what does qhse stand for': 'QHSE stands for Quality, Health, Safety, and Environment. It encompasses all practices aimed at ensuring quality, safety, and environmental compliance within an organization.',
    'why is qhse important': 'QHSE is important because it helps organizations ensure the safety of employees, maintain quality standards, comply with regulations, and minimize environmental impact.',
    'describe qhse': 'QHSE is an integrated management approach focusing on maintaining quality, ensuring the health and safety of workers, and protecting the environment.',
    'what are the key components of qhse': 'The key components of QHSE are Quality Management, Health Management, Safety Management, and Environmental Management. Together, they ensure an organization\'s operations meet high standards.',
    'what is the purpose of qhse': 'The purpose of QHSE is to promote a safe and healthy work environment, maintain high-quality standards, and minimize negative environmental impacts.',
    'how does qhse benefit an organization': 'QHSE benefits an organization by reducing risks, ensuring compliance, improving operational efficiency, and enhancing corporate reputation.',
    'what are qhse objectives': 'QHSE objectives typically include achieving zero accidents, ensuring regulatory compliance, improving product and service quality, and reducing environmental impact.',
    'what is the role of qhse in an organization': 'The role of QHSE in an organization is to establish and maintain standards that protect employee health and safety, ensure quality, and minimize environmental impact.',
    'what is a qhse system': 'A QHSE system is a structured framework used by organizations to manage quality, health, safety, and environmental responsibilities. It integrates policies, procedures, and processes to achieve QHSE objectives.',
    'what are qhse responsibilities': 'QHSE responsibilities include ensuring compliance with regulations, conducting risk assessments, providing training, and monitoring and improving QHSE performance.',
    'what are qhse principles': 'QHSE principles are the foundational guidelines that drive an organization\'s commitment to quality, health, safety, and environmental stewardship. These principles include risk management, continuous improvement, and stakeholder engagement.',
    'what is qhse management': 'QHSE management involves the administration and oversight of policies and practices that ensure quality, health, safety, and environmental objectives are met within an organization.',
    'how is qhse measured': 'QHSE is measured through key performance indicators (KPIs) such as incident rates, audit results, customer satisfaction, and environmental impact assessments.',
    'what is a qhse audit': 'A QHSE audit is a systematic evaluation of an organization\'s compliance with quality, health, safety, and environmental standards. It identifies areas of improvement and ensures adherence to regulations.',
    'what is the difference between qhse and hse': 'HSE focuses on Health, Safety, and Environment, while QHSE includes an additional emphasis on Quality, integrating quality management into the overall framework.',
    'what industries use qhse': 'Industries such as manufacturing, oil and gas, construction, pharmaceuticals, and food and beverage commonly use QHSE to ensure safety, quality, and environmental compliance.',
    'who is responsible for qhse in an organization': 'Responsibility for QHSE typically lies with a dedicated QHSE manager or team, but it is ultimately shared across all levels of the organization to ensure a safe and compliant work environment.',
    'how does qhse relate to corporate social responsibility': 'QHSE is closely related to Corporate Social Responsibility (CSR) as both focus on ethical practices, including protecting employees, customers, and the environment, while also delivering high-quality products and services.',
    'what is the history of qhse': 'The concept of QHSE evolved from the need to integrate quality management with health, safety, and environmental practices, especially in industries where safety and environmental impact are critical concerns.',

    // hard coded
    'define qhse': 'QHSE stands for Quality, Health, Safety, and Environment. It encompasses all practices and standards aimed at ensuring quality, safety, and environmental compliance within an organization.',
    'what is the importance of qhse': 'The importance of QHSE lies in its ability to improve organizational performance, ensure compliance with legal and regulatory requirements, enhance employee safety, and minimize environmental impact.',
    'define qhse standards': 'QHSE standards are guidelines and requirements set to ensure quality, health, safety, and environmental management. Common standards include ISO 9001 for quality, ISO 45001 for occupational health and safety, and ISO 14001 for environmental management.',
    'how to implement qhse': 'Implementing QHSE involves establishing policies and procedures, conducting risk assessments, providing training, monitoring performance, and ensuring compliance with relevant standards and regulations.',
    'define qhse policy': 'A QHSE policy outlines an organization\'s commitment to quality, health, safety, and environmental management. It sets the framework for managing QHSE aspects and achieving continuous improvement.',
    'explain qhse': 'QHSE stands for Quality, Health, Safety, and Environment. It encompasses all practices and standards aimed at ensuring quality, safety, and environmental compliance within an organization.',
    'explain importance of qhse': 'The importance of QHSE lies in its ability to improve organizational performance, ensure compliance with legal and regulatory requirements, enhance employee safety, and minimize environmental impact.',
    'explain qhse standards': 'QHSE standards are guidelines and requirements set to ensure quality, health, safety, and environmental management. Common standards include ISO 9001 for quality, ISO 45001 for occupational health and safety, and ISO 14001 for environmental management.',
    'explain qhse policy': 'A QHSE policy outlines an organization\'s commitment to quality, health, safety, and environmental management. It sets the framework for managing QHSE aspects and achieving continuous improvement.',
    'what is qhse': 'QHSE stands for Quality, Health, Safety, and Environment. It encompasses all practices and standards aimed at ensuring quality, safety, and environmental compliance within an organization.',
    'what are qhse standards': 'QHSE standards are guidelines and requirements set to ensure quality, health, safety, and environmental management. Common standards include ISO 9001 for quality, ISO 45001 for occupational health and safety, and ISO 14001 for environmental management.',
    'what is qhse policy': 'A QHSE policy outlines an organization\'s commitment to quality, health, safety, and environmental management. It sets the framework for managing QHSE aspects and achieving continuous improvement.',

    // hard coded
    'explain audit': 'The Audit and Inspection Module helps in managing audits and inspections effectively. You can schedule audits, track findings, and generate reports.',
    'explain audit findings': 'Audit findings are the results of an audit process that identifies non-conformities, areas for improvement, and compliance with standards.',
    'explain audit schedule': 'You can schedule audits to ensure regular review and compliance with QHSE standards.',
    'explain audit checklist': 'An audit checklist includes all the criteria and areas to be reviewed during an audit, helping ensure a thorough evaluation.',
    'explain internal audit': 'Internal audits are conducted by the organization to evaluate its own QHSE processes and ensure compliance with internal policies and standards.',
    'explain external audit': 'External audits are conducted by third-party organizations to assess compliance with QHSE standards and regulations.',
    'explain audit report': 'The audit report provides a summary of the findings, including non-conformities, areas for improvement, and recommendations for corrective actions.',
    'define audit': 'The Audit and Inspection Module helps in managing audits and inspections effectively. You can schedule audits, track findings, and generate reports.',
    'define audit findings': 'Audit findings are the results of an audit process that identifies non-conformities, areas for improvement, and compliance with standards.',
    'define audit schedule': 'You can schedule audits to ensure regular review and compliance with QHSE standards.',
    'define audit checklist': 'An audit checklist includes all the criteria and areas to be reviewed during an audit, helping ensure a thorough evaluation.',
    'define internal audit': 'Internal audits are conducted by the organization to evaluate its own QHSE processes and ensure compliance with internal policies and standards.',
    'define external audit': 'External audits are conducted by third-party organizations to assess compliance with QHSE standards and regulations.',
    'define audit report': 'The audit report provides a summary of the findings, including non-conformities, areas for improvement, and recommendations for corrective actions.',
    'what is audit': 'The Audit and Inspection Module helps in managing audits and inspections effectively. You can schedule audits, track findings, and generate reports.',
    'what is audit findings': 'Audit findings are the results of an audit process that identifies non-conformities, areas for improvement, and compliance with standards.',
    'what is audit schedule': 'You can schedule audits to ensure regular review and compliance with QHSE standards.',
    'what is audit checklist': 'An audit checklist includes all the criteria and areas to be reviewed during an audit, helping ensure a thorough evaluation.',
    'what is internal audit': 'Internal audits are conducted by the organization to evaluate its own QHSE processes and ensure compliance with internal policies and standards.',
    'what is external audit': 'External audits are conducted by third-party organizations to assess compliance with QHSE standards and regulations.',
    'what is audit report': 'The audit report provides a summary of the findings, including non-conformities, areas for improvement, and recommendations for corrective actions.',

    // hard coded
    'explain document management': 'The Document Management System ensures that all important documents are stored, managed, and retrieved efficiently.',
    'explain document control': 'Document control ensures that documents are properly managed, updated, and accessible only to authorized personnel.',
    'explain document retention': 'Document retention policies determine how long documents should be kept before they are disposed of or archived.',
    'explain document versioning': 'Document versioning tracks changes to documents over time, ensuring that the latest version is always available.',
    'explain document approval': 'Document approval workflows ensure that documents are reviewed and approved by the appropriate personnel before they are finalized.',
    'explain document access': 'Document access controls ensure that sensitive documents are accessible only to authorized users.',
    'explain document retrieval': 'Document retrieval systems allow users to quickly search for and retrieve documents based on keywords, metadata, or other criteria.',
    'define document management': 'The Document Management System ensures that all important documents are stored, managed, and retrieved efficiently.',
    'define document control': 'Document control ensures that documents are properly managed, updated, and accessible only to authorized personnel.',
    'define document retention': 'Document retention policies determine how long documents should be kept before they are disposed of or archived.',
    'define document versioning': 'Document versioning tracks changes to documents over time, ensuring that the latest version is always available.',
    'define document approval': 'Document approval workflows ensure that documents are reviewed and approved by the appropriate personnel before they are finalized.',
    'define document access': 'Document access controls ensure that sensitive documents are accessible only to authorized users.',
    'define document retrieval': 'Document retrieval systems allow users to quickly search for and retrieve documents based on keywords, metadata, or other criteria.',
    'what is document management': 'The Document Management System ensures that all important documents are stored, managed, and retrieved efficiently.',
    'what is document control': 'Document control ensures that documents are properly managed, updated, and accessible only to authorized personnel.',
    'what is document retention': 'Document retention policies determine how long documents should be kept before they are disposed of or archived.',
    'what is document versioning': 'Document versioning tracks changes to documents over time, ensuring that the latest version is always available.',
    'what is document approval': 'Document approval workflows ensure that documents are reviewed and approved by the appropriate personnel before they are finalized.',
    'what is document access': 'Document access controls ensure that sensitive documents are accessible only to authorized users.',
    'what is document retrieval': 'Document retrieval systems allow users to quickly search for and retrieve documents based on keywords, metadata, or other criteria.',

    //
    'explain management of change': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'explain moc process': 'The MOC process involves identifying, evaluating, and implementing changes in a controlled manner to minimize risks.',
    'explain moc approval': 'MOC approval is required before any significant change can be implemented, ensuring that all risks are assessed and managed.',
    'explain moc documentation': 'MOC documentation includes records of the proposed change, risk assessment, approvals, and implementation steps.',
    'explain moc training': 'MOC training ensures that all employees are aware of changes and understand how to implement them safely.',
    'explain moc communication': 'MOC communication involves informing all relevant stakeholders about changes and how they will be implemented.',
    'explain moc follow-up': 'MOC follow-up ensures that changes are implemented as planned and that any issues are addressed promptly.',
    'define management of change': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'define moc process': 'The MOC process involves identifying, evaluating, and implementing changes in a controlled manner to minimize risks.',
    'define moc approval': 'MOC approval is required before any significant change can be implemented, ensuring that all risks are assessed and managed.',
    'define moc documentation': 'MOC documentation includes records of the proposed change, risk assessment, approvals, and implementation steps.',
    'define moc training': 'MOC training ensures that all employees are aware of changes and understand how to implement them safely.',
    'define moc communication': 'MOC communication involves informing all relevant stakeholders about changes and how they will be implemented.',
    'define moc follow-up': 'MOC follow-up ensures that changes are implemented as planned and that any issues are addressed promptly.',
    'what is management of change': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'what is moc process': 'The MOC process involves identifying, evaluating, and implementing changes in a controlled manner to minimize risks.',
    'what is moc approval': 'MOC approval is required before any significant change can be implemented, ensuring that all risks are assessed and managed.',
    'what is moc documentation': 'MOC documentation includes records of the proposed change, risk assessment, approvals, and implementation steps.',
    'what is moc training': 'MOC training ensures that all employees are aware of changes and understand how to implement them safely.',
    'what is moc communication': 'MOC communication involves informing all relevant stakeholders about changes and how they will be implemented.',
    'what is moc follow-up': 'MOC follow-up ensures that changes are implemented as planned and that any issues are addressed promptly.',
    'moc': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'what is moc': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'explain moc': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',
    'define moc': 'The Management of Change Module tracks changes in processes or procedures to ensure that they are implemented safely and effectively.',

    //hard coded
    'explain asset management': 'The Asset Management Module helps in managing the lifecycle of assets, including maintenance and performance monitoring.',
    'explain asset tracking': 'The Asset Tracking System helps in monitoring and managing the location, status, and condition of assets in real-time.',
    'explain maintenance management': 'The Maintenance Management Module schedules and tracks maintenance activities to ensure assets are operating efficiently and to prevent downtime.',
    'explain inventory management': 'The Inventory Management System keeps track of all assets, including their quantity, location, and usage, to optimize inventory levels.',
    'explain lifecycle management': 'The Asset Lifecycle Management Module oversees the entire lifecycle of assets from acquisition to disposal, ensuring maximum value and compliance.',
    'explain financial management': 'The Financial Management System tracks the financial performance of assets, including depreciation, cost allocation, and return on investment.',
    'explain performance monitoring': 'The Performance Monitoring System tracks the performance of assets to ensure they meet operational and strategic goals.',
    'explain procurement': 'The Procurement Module manages the acquisition of assets, ensuring cost-effectiveness and compliance with procurement policies.',
    'explain disposal': 'The Asset Disposal Module handles the end-of-life process for assets, including decommissioning, sale, or recycling, in a compliant and cost-effective manner.',
    'define asset management': 'The Asset Management Module helps in managing the lifecycle of assets, including maintenance and performance monitoring.',
    'define asset tracking': 'The Asset Tracking System helps in monitoring and managing the location, status, and condition of assets in real-time.',
    'define maintenance management': 'The Maintenance Management Module schedules and tracks maintenance activities to ensure assets are operating efficiently and to prevent downtime.',
    'define inventory management': 'The Inventory Management System keeps track of all assets, including their quantity, location, and usage, to optimize inventory levels.',
    'define lifecycle management': 'The Asset Lifecycle Management Module oversees the entire lifecycle of assets from acquisition to disposal, ensuring maximum value and compliance.',
    'define financial management': 'The Financial Management System tracks the financial performance of assets, including depreciation, cost allocation, and return on investment.',
    'define performance monitoring': 'The Performance Monitoring System tracks the performance of assets to ensure they meet operational and strategic goals.',
    'define procurement': 'The Procurement Module manages the acquisition of assets, ensuring cost-effectiveness and compliance with procurement policies.',
    'define disposal': 'The Asset Disposal Module handles the end-of-life process for assets, including decommissioning, sale, or recycling, in a compliant and cost-effective manner.',
    'what is asset management': 'The Asset Management Module helps in managing the lifecycle of assets, including maintenance and performance monitoring.',
    'what is asset tracking': 'The Asset Tracking System helps in monitoring and managing the location, status, and condition of assets in real-time.',
    'what is maintenance management': 'The Maintenance Management Module schedules and tracks maintenance activities to ensure assets are operating efficiently and to prevent downtime.',
    'what is inventory management': 'The Inventory Management System keeps track of all assets, including their quantity, location, and usage, to optimize inventory levels.',
    'what is lifecycle management': 'The Asset Lifecycle Management Module oversees the entire lifecycle of assets from acquisition to disposal, ensuring maximum value and compliance.',
    'what is financial management': 'The Financial Management System tracks the financial performance of assets, including depreciation, cost allocation, and return on investment.',
    'what is performance monitoring': 'The Performance Monitoring System tracks the performance of assets to ensure they meet operational and strategic goals.',
    'what is procurement': 'The Procurement Module manages the acquisition of assets, ensuring cost-effectiveness and compliance with procurement policies.',
    'what is disposal': 'The Asset Disposal Module handles the end-of-life process for assets, including decommissioning, sale, or recycling, in a compliant and cost-effective manner.',

    //hard coded
    'explain training': 'The Training Module ensures that all employees receive the necessary training to meet compliance requirements and improve safety practices.',
    'explain training programs': 'Training programs are designed to enhance employee skills and knowledge in specific areas to ensure competency and compliance with safety and regulatory standards.',
    'define training': 'The Training Module ensures that all employees receive the necessary training to meet compliance requirements and improve safety practices.',
    'define training programs': 'Training programs are designed to enhance employee skills and knowledge in specific areas to ensure competency and compliance with safety and regulatory standards.',
    'what is training': 'The Training Module ensures that all employees receive the necessary training to meet compliance requirements and improve safety practices.',
    'what is training programs': 'Training programs are designed to enhance employee skills and knowledge in specific areas to ensure competency and compliance with safety and regulatory standards.',

    //hard coded
    'explain compliance': 'Compliance management involves ensuring that all processes and procedures meet regulatory requirements and industry standards.',
    'explain policy management': 'Policy management involves creating, updating, and communicating policies to ensure adherence to organizational and regulatory standards.',
    'explain regulatory requirements': 'Regulatory requirements are rules and regulations established by authorities that organizations must comply with to operate legally and safely.',
    'define compliance': 'Compliance management involves ensuring that all processes and procedures meet regulatory requirements and industry standards.',
    'define policy management': 'Policy management involves creating, updating, and communicating policies to ensure adherence to organizational and regulatory standards.',
    'define regulatory requirements': 'Regulatory requirements are rules and regulations established by authorities that organizations must comply with to operate legally and safely.',
    'what is compliance': 'Compliance management involves ensuring that all processes and procedures meet regulatory requirements and industry standards.',
    'what is policy management': 'Policy management involves creating, updating, and communicating policies to ensure adherence to organizational and regulatory standards.',
    'what are regulatory requirements': 'Regulatory requirements are rules and regulations established by authorities that organizations must comply with to operate legally and safely.',

    //hard coded
    'explain observation': 'The HSE Observation System helps in recording and analyzing observations related to health, safety, and environmental practices.',
    'explain observation types': 'Observations can be categorized into safety observations, compliance observations, and operational observations. Each type helps address specific aspects of the workplace.',
    'explain handling observations': 'Handling observations involves documenting the details, assessing the significance, and taking corrective actions if needed. It\'s important to ensure that observations are followed up to improve safety and compliance.',
    'explain observation frequency': 'The frequency of observations depends on your organization\'s policies and the specific needs of your workplace. Regular observations help in identifying potential hazards and maintaining safety standards.',
    'explain follow-up actions': 'Follow-up actions on observations include reviewing the reported issue, implementing corrective measures, and monitoring the effectiveness of these measures to prevent recurrence.',
    'explain observation training': 'Training on observations involves educating employees on how to identify and report observations effectively. This training ensures that all personnel are aware of the importance of observations and how to document them properly.',
    'define observation': 'The HSE Observation System helps in recording and analyzing observations related to health, safety, and environmental practices.',
    'define observation types': 'Observations can be categorized into safety observations, compliance observations, and operational observations. Each type helps address specific aspects of the workplace.',
    'define handling observations': 'Handling observations involves documenting the details, assessing the significance, and taking corrective actions if needed. It\'s important to ensure that observations are followed up to improve safety and compliance.',
    'define observation frequency': 'The frequency of observations depends on your organization\'s policies and the specific needs of your workplace. Regular observations help in identifying potential hazards and maintaining safety standards.',
    'define follow-up actions': 'Follow-up actions on observations include reviewing the reported issue, implementing corrective measures, and monitoring the effectiveness of these measures to prevent recurrence.',
    'define observation training': 'Training on observations involves educating employees on how to identify and report observations effectively. This training ensures that all personnel are aware of the importance of observations and how to document them properly.',
    'what is observation': 'The HSE Observation System helps in recording and analyzing observations related to health, safety, and environmental practices.',
    'what are observation types': 'Observations can be categorized into safety observations, compliance observations, and operational observations. Each type helps address specific aspects of the workplace.',
    'what are handling observations': 'Handling observations involves documenting the details, assessing the significance, and taking corrective actions if needed. It\'s important to ensure that observations are followed up to improve safety and compliance.',
    'what is observation frequency': 'The frequency of observations depends on your organization\'s policies and the specific needs of your workplace. Regular observations help in identifying potential hazards and maintaining safety standards.',
    'what are follow-up actions': 'Follow-up actions on observations include reviewing the reported issue, implementing corrective measures, and monitoring the effectiveness of these measures to prevent recurrence.',
    'what is observation training': 'Training on observations involves educating employees on how to identify and report observations effectively. This training ensures that all personnel are aware of the importance of observations and how to document them properly.',

    //hard coded
    'explain incident': 'The HSE Incident/Accident Management System allows you to report, track, and analyze incidents and accidents to improve safety and compliance.',
    'explain incident reporting': 'Incident reporting involves documenting the details of an incident as soon as it occurs. This includes the date, time, location, individuals involved, and a description of the event.',
    'explain incident investigation': 'Incident investigation involves analyzing the causes of an incident to identify corrective actions and prevent recurrence. This process typically includes root cause analysis and implementation of preventive measures.',
    'explain incident response': 'Incident response includes the actions taken immediately after an incident to address the situation, ensure safety, and mitigate any potential impacts.',
    'explain incident tracking': 'Incident tracking involves monitoring the progress of incident investigations, corrective actions, and resolution status to ensure all incidents are managed effectively.',
    'explain incident analysis': 'Incident analysis involves reviewing incident data to identify trends, patterns, and areas for improvement. This helps in enhancing safety measures and reducing the likelihood of future incidents.',
    'explain incident follow-up': 'Incident follow-up includes verifying that corrective actions have been implemented and assessing their effectiveness in preventing similar incidents in the future.',
    'define incident': 'The HSE Incident/Accident Management System allows you to report, track, and analyze incidents and accidents to improve safety and compliance.',
    'define incident reporting': 'Incident reporting involves documenting the details of an incident as soon as it occurs. This includes the date, time, location, individuals involved, and a description of the event.',
    'define incident investigation': 'Incident investigation involves analyzing the causes of an incident to identify corrective actions and prevent recurrence. This process typically includes root cause analysis and implementation of preventive measures.',
    'define incident response': 'Incident response includes the actions taken immediately after an incident to address the situation, ensure safety, and mitigate any potential impacts.',
    'define incident tracking': 'Incident tracking involves monitoring the progress of incident investigations, corrective actions, and resolution status to ensure all incidents are managed effectively.',
    'define incident analysis': 'Incident analysis involves reviewing incident data to identify trends, patterns, and areas for improvement. This helps in enhancing safety measures and reducing the likelihood of future incidents.',
    'define incident follow-up': 'Incident follow-up includes verifying that corrective actions have been implemented and assessing their effectiveness in preventing similar incidents in the future.',
    'what is incident': 'The HSE Incident/Accident Management System allows you to report, track, and analyze incidents and accidents to improve safety and compliance.',
    'what is incident reporting': 'Incident reporting involves documenting the details of an incident as soon as it occurs. This includes the date, time, location, individuals involved, and a description of the event.',
    'what is incident investigation': 'Incident investigation involves analyzing the causes of an incident to identify corrective actions and prevent recurrence. This process typically includes root cause analysis and implementation of preventive measures.',
    'what is incident response': 'Incident response includes the actions taken immediately after an incident to address the situation, ensure safety, and mitigate any potential impacts.',
    'what is incident tracking': 'Incident tracking involves monitoring the progress of incident investigations, corrective actions, and resolution status to ensure all incidents are managed effectively.',
    'what is incident analysis': 'Incident analysis involves reviewing incident data to identify trends, patterns, and areas for improvement. This helps in enhancing safety measures and reducing the likelihood of future incidents.',
    'what is incident follow-up': 'Incident follow-up includes verifying that corrective actions have been implemented and assessing their effectiveness in preventing similar incidents in the future.',

    'define root cause analysis': 'Root cause analysis is a method used to identify the underlying causes of problems or incidents to prevent recurrence. It involves analyzing the contributing factors and implementing corrective actions.',
    'define causal analysis': 'Causal analysis involves examining the causes and effects of a problem to understand the underlying issues and develop solutions.',
    'define problem-solving': 'Problem-solving involves identifying, analyzing, and resolving issues to improve processes and prevent future problems.',
    'define corrective actions': 'Corrective actions are steps taken to address the root cause of a problem or incident to prevent it from happening again. This may include changes to processes, procedures, or training.',
    'define preventive actions': 'Preventive actions are measures implemented to reduce the likelihood of a problem or incident occurring in the future. This can involve process improvements, additional training, or changes in procedures.',
    'explain root cause analysis': 'Root cause analysis is a method used to identify the underlying causes of problems or incidents to prevent recurrence. It involves analyzing the contributing factors and implementing corrective actions.',
    'explain causal analysis': 'Causal analysis involves examining the causes and effects of a problem to understand the underlying issues and develop solutions.',
    'explain problem-solving': 'Problem-solving involves identifying, analyzing, and resolving issues to improve processes and prevent future problems.',
    'explain corrective actions': 'Corrective actions are steps taken to address the root cause of a problem or incident to prevent it from happening again. This may include changes to processes, procedures, or training.',
    'explain preventive actions': 'Preventive actions are measures implemented to reduce the likelihood of a problem or incident occurring in the future. This can involve process improvements, additional training, or changes in procedures.',
    'what is root cause analysis': 'Root cause analysis is a method used to identify the underlying causes of problems or incidents to prevent recurrence. It involves analyzing the contributing factors and implementing corrective actions.',
    'what is causal analysis': 'Causal analysis involves examining the causes and effects of a problem to understand the underlying issues and develop solutions.',
    'what is problem-solving': 'Problem-solving involves identifying, analyzing, and resolving issues to improve processes and prevent future problems.',
    'what is corrective actions': 'Corrective actions are steps taken to address the root cause of a problem or incident to prevent it from happening again. This may include changes to processes, procedures, or training.',
    'what is preventive actions': 'Preventive actions are measures implemented to reduce the likelihood of a problem or incident occurring in the future. This can involve process improvements, additional training, or changes in procedures.',

    'explain feedback': 'Your feedback is valuable to us. It helps improve our processes and services. Please let us know your thoughts or suggestions!',
    'explain feedback process': 'The feedback process involves collecting, reviewing, and acting on feedback provided by users to enhance the quality of services and address any issues or concerns.',
    'explain feedback implementation': 'Feedback implementation involves integrating user feedback into processes, policies, or systems to improve performance and user satisfaction.',
    'define feedback': 'Your feedback is valuable to us. It helps improve our processes and services. Please let us know your thoughts or suggestions!',
    'define feedback process': 'The feedback process involves collecting, reviewing, and acting on feedback provided by users to enhance the quality of services and address any issues or concerns.',
    'define feedback implementation': 'Feedback implementation involves integrating user feedback into processes, policies, or systems to improve performance and user satisfaction.',
    'what is feedback': 'Your feedback is valuable to us. It helps improve our processes and services. Please let us know your thoughts or suggestions!',
    'what is feedback process': 'The feedback process involves collecting, reviewing, and acting on feedback provided by users to enhance the quality of services and address any issues or concerns.',
    'what is feedback implementation': 'Feedback implementation involves integrating user feedback into processes, policies, or systems to improve performance and user satisfaction.',

    //hard coded
    'define report': 'The Reports Module provides comprehensive reporting capabilities to track performance, compliance, and other key metrics.',
    'define report generation': 'Report generation involves creating detailed reports on various aspects of your operations, including audits, incidents, and compliance status.',
    'define report analysis': 'Report analysis involves reviewing and interpreting report data to gain insights and make informed decisions.',
    'define report customization': 'Report customization allows you to tailor reports to meet specific needs or preferences, such as including or excluding certain data, formatting, or layout options.',
    'define report distribution': 'Report distribution involves sharing reports with relevant stakeholders through various channels, such as email, dashboards, or printed copies.',
    'explain report': 'The Reports Module provides comprehensive reporting capabilities to track performance, compliance, and other key metrics.',
    'explain report generation': 'Report generation involves creating detailed reports on various aspects of your operations, including audits, incidents, and compliance status.',
    'explain report analysis': 'Report analysis involves reviewing and interpreting report data to gain insights and make informed decisions.',
    'explain report customization': 'Report customization allows you to tailor reports to meet specific needs or preferences, such as including or excluding certain data, formatting, or layout options.',
    'explain report distribution': 'Report distribution involves sharing reports with relevant stakeholders through various channels, such as email, dashboards, or printed copies.',
    'what is report': 'The Reports Module provides comprehensive reporting capabilities to track performance, compliance, and other key metrics.',
    'what is report generation': 'Report generation involves creating detailed reports on various aspects of your operations, including audits, incidents, and compliance status.',
    'what is report analysis': 'Report analysis involves reviewing and interpreting report data to gain insights and make informed decisions.',
    'what is report customization': 'Report customization allows you to tailor reports to meet specific needs or preferences, such as including or excluding certain data, formatting, or layout options.',
    'what is report distribution': 'Report distribution involves sharing reports with relevant stakeholders through various channels, such as email, dashboards, or printed copies.',

    //hard coded
    'explain safety': 'Safety management involves implementing practices and procedures to ensure a safe working environment and reduce the risk of accidents and incidents.',
    'explain safety measures': 'Safety measures are actions or protocols put in place to protect employees and minimize hazards in the workplace.',
    'explain safety protocols': 'Safety protocols are established guidelines and procedures designed to ensure safety and compliance with regulations.',
    'explain safety training': 'Safety training involves educating employees on safety procedures, protocols, and best practices to ensure a safe working environment.',
    'explain safety policies': 'Safety policies outline the rules and expectations for maintaining a safe workplace, including reporting hazards and responding to emergencies.',
    'explain emergency preparedness': 'Emergency preparedness involves planning and training for potential emergencies to ensure a prompt and effective response.',
    'define safety': 'Safety management involves implementing practices and procedures to ensure a safe working environment and reduce the risk of accidents and incidents.',
    'define safety measures': 'Safety measures are actions or protocols put in place to protect employees and minimize hazards in the workplace.',
    'define safety protocols': 'Safety protocols are established guidelines and procedures designed to ensure safety and compliance with regulations.',
    'define safety training': 'Safety training involves educating employees on safety procedures, protocols, and best practices to ensure a safe working environment.',
    'define safety policies': 'Safety policies outline the rules and expectations for maintaining a safe workplace, including reporting hazards and responding to emergencies.',
    'define emergency preparedness': 'Emergency preparedness involves planning and training for potential emergencies to ensure a prompt and effective response.',
    'what is safety': 'Safety management involves implementing practices and procedures to ensure a safe working environment and reduce the risk of accidents and incidents.',
    'what are safety measures': 'Safety measures are actions or protocols put in place to protect employees and minimize hazards in the workplace.',
    'what are safety protocols': 'Safety protocols are established guidelines and procedures designed to ensure safety and compliance with regulations.',
    'what is safety training': 'Safety training involves educating employees on safety procedures, protocols, and best practices to ensure a safe working environment.',
    'what are safety policies': 'Safety policies outline the rules and expectations for maintaining a safe workplace, including reporting hazards and responding to emergencies.',
    'what are emergency preparedness': 'Emergency preparedness involves planning and training for potential emergencies to ensure a prompt and effective response.',

    //hard coded
    'explain health': 'Health management involves promoting and maintaining the physical and mental well-being of employees within the organization.',
    'explain health policies': 'Health policies outline the guidelines and procedures for maintaining employee health and well-being, including medical support, wellness programs, and health assessments.',
    'explain health programs': 'Health programs are initiatives designed to support and improve employee health, such as wellness programs, health screenings, and mental health support.',
    'explain health and safety': 'Health and safety management encompasses practices and procedures to protect employees, physical and mental health, ensuring a safe and healthy work environment.',
    'explain mental health': 'Mental health management involves supporting employees, mental well- being through programs, resources, and policies designed to promote mental wellness and address mental health concerns.',
    'explain occupational health': 'Occupational health focuses on preventing and managing health issues related to the workplace, including monitoring and addressing health risks and promoting a healthy work environment.',
    'explain wellness': 'Wellness programs aim to enhance employees, overall health and well - being through various activities and initiatives, such as fitness programs, nutrition guidance, and stress management.',
    'define health': 'Health management involves promoting and maintaining the physical and mental well-being of employees within the organization.',
    'define health policies': 'Health policies outline the guidelines and procedures for maintaining employee health and well-being, including medical support, wellness programs, and health assessments.',
    'define health programs': 'Health programs are initiatives designed to support and improve employee health, such as wellness programs, health screenings, and mental health support.',
    'define health and safety': 'Health and safety management encompasses practices and procedures to protect employees, physical and mental health, ensuring a safe and healthy work environment.',
    'define mental health': 'Mental health management involves supporting employees, mental well- being through programs, resources, and policies designed to promote mental wellness and address mental health concerns.',
    'define occupational health': 'Occupational health focuses on preventing and managing health issues related to the workplace, including monitoring and addressing health risks and promoting a healthy work environment.',
    'define wellness': 'Wellness programs aim to enhance employees, overall health and well - being through various activities and initiatives, such as fitness programs, nutrition guidance, and stress management.',
    'what is health': 'Health management involves promoting and maintaining the physical and mental well-being of employees within the organization.',
    'what are health policies': 'Health policies outline the guidelines and procedures for maintaining employee health and well-being, including medical support, wellness programs, and health assessments.',
    'what are health programs': 'Health programs are initiatives designed to support and improve employee health, such as wellness programs, health screenings, and mental health support.',
    'what is health and safety': 'Health and safety management encompasses practices and procedures to protect employees, physical and mental health, ensuring a safe and healthy work environment.',
    'what is mental health': 'Mental health management involves supporting employees, mental well- being through programs, resources, and policies designed to promote mental wellness and address mental health concerns.',
    'what is occupational health': 'Occupational health focuses on preventing and managing health issues related to the workplace, including monitoring and addressing health risks and promoting a healthy work environment.',
    'what is wellness': 'Wellness programs aim to enhance employees, overall health and well - being through various activities and initiatives, such as fitness programs, nutrition guidance, and stress management.',
};

// Export responses
module.exports = responses;